# Generated by Django 2.0 on 2018-03-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadotramite',
            table='estado_tramite',
        ),
        migrations.AlterModelTable(
            name='tramite',
            table='tramite',
        ),
    ]
