# Generated by Django 2.0 on 2018-05-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaTipoPostgrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asignatura_tipoPostgrado',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.IntegerField()),
                ('horario_dia', models.CharField(choices=[('0', 'lunes'), ('1', 'martes'), ('2', 'miercoles'), ('3', 'jueves'), ('4', 'viernes'), ('5', 'sabado'), ('6', 'domingo')], max_length=1)),
                ('horario_hora', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'docente_asignatura',
            },
        ),
        migrations.CreateModel(
            name='EstudianteAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_definitiva', models.IntegerField()),
                ('retirado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['periodo_estudiante__periodo__id'],
                'db_table': 'estudiante_asignatura',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField()),
            ],
            options={
                'db_table': 'periodo_estudiante',
            },
        ),
    ]
