# Generated by Django 2.0 on 2018-05-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('relacion', '0001_initial'),
        ('asignatura', '0001_initial'),
        ('periodo', '0002_periodo_tipo_postgrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Estudiante'),
        ),
        migrations.AddField(
            model_name='periodoestudiante',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo'),
        ),
        migrations.AddField(
            model_name='estudianteasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.Asignatura'),
        ),
        migrations.AddField(
            model_name='estudianteasignatura',
            name='periodo_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacion.PeriodoEstudiante'),
        ),
        migrations.AddField(
            model_name='docenteasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.Asignatura'),
        ),
        migrations.AddField(
            model_name='docenteasignatura',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.PersonalDocente'),
        ),
        migrations.AddField(
            model_name='docenteasignatura',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo'),
        ),
        migrations.AddField(
            model_name='asignaturatipopostgrado',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.Asignatura'),
        ),
        migrations.AddField(
            model_name='asignaturatipopostgrado',
            name='tipo_postgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.TipoPostgrado'),
        ),
    ]
