# Generated by Django 2.0 on 2018-05-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0002_auto_20180502_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docenteasignatura',
            old_name='aula',
            new_name='piso',
        ),
    ]
