# Generated by Django 2.0 on 2018-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0003_auto_20180308_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteasignatura',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
