# Generated by Django 2.0 on 2018-04-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0004_estudianteasignatura_retirado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudianteasignatura',
            options={'ordering': ['periodo_estudiante__periodo__id']},
        ),
    ]
