# Generated by Django 2.0 on 2017-12-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=8)),
                ('contrasena', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=60)),
                ('correo_alternativo', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_trabajo', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
