# Generated by Django 2.0 on 2017-12-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(editable=False, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_alternativo', models.EmailField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_trabajo', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=100)),
                ('direcccion', models.TextField()),
                ('id_estado_estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.EstadoEstudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPostgrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_tipo_postgrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.TipoPostgrado'),
        ),
    ]
