# Generated by Django 2.0 on 2018-05-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
