# Generated by Django 2.0 on 2018-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopostgrado',
            name='asignaturas_por_periodo',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='tipopostgrado',
            name='tipo',
            field=models.CharField(max_length=150),
        ),
    ]
