# Generated by Django 2.0 on 2018-01-07 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldocente',
            old_name='direcccion',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2018, 1, 7)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
