# Generated by Django 2.0 on 2018-04-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180412_2254'),
        ('usuario', '0002_auto_20180413_0210'),
    ]

    operations = [
    ]
