# Generated by Django 2.0 on 2017-12-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20171221_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(editable=False, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_alternativo', models.EmailField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_trabajo', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(editable=False, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_alternativo', models.EmailField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_trabajo', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(editable=False, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_alternativo', models.EmailField(max_length=60)),
                ('celular', models.CharField(max_length=14)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_trabajo', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.FileField(upload_to='')),
                ('direcccion', models.TextField()),
                ('rif', models.FileField(upload_to='')),
                ('curriculum', models.FileField(upload_to='')),
                ('permiso_ingresos', models.FileField(upload_to='')),
                ('coordinador', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
