# Generated by Django 2.0 on 2018-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=25),
        ),
    ]
