# Generated by Django 2.0 on 2017-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20171221_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contrasena',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='contrasena',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personaldocente',
            name='contrasena',
            field=models.CharField(max_length=64),
        ),
    ]
