# Generated by Django 2.0 on 2018-04-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_merge_20180414_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopostgrado',
            name='asignaturas_por_periodo',
        ),
    ]
