# Generated by Django 2.0 on 2018-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180508_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldocente',
            name='coordinador_tipo_postgrado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
