# Generated by Django 2.0 on 2018-05-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_personaldocente_coordinador_tipo_postgrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldocente',
            name='coordinador_tipo_postgrado',
        ),
        migrations.AddField(
            model_name='personaldocente',
            name='tipo_postgrado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.TipoPostgrado'),
        ),
    ]
