# Generated by Django 2.0 on 2018-01-07 19:15

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to=usuario.models.user_directory_path),
        ),
    ]
