# Generated by Django 2.0 on 2018-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180105_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
