# Generated by Django 2.0 on 2018-01-07 19:16

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180107_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='sisgiu/no_avatar.jpg', null=True, upload_to=usuario.models.user_directory_path),
        ),
    ]
