# Generated by Django 2.0 on 2018-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20180105_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
