# Generated by Django 2.0 on 2018-01-07 23:08

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20180107_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldocente',
            name='curriculum',
            field=models.FileField(upload_to=usuario.models.user_directory_path_subuser),
        ),
        migrations.AlterField(
            model_name='personaldocente',
            name='permiso_ingresos',
            field=models.FileField(upload_to=usuario.models.user_directory_path_subuser),
        ),
        migrations.AlterField(
            model_name='personaldocente',
            name='rif',
            field=models.FileField(upload_to=usuario.models.user_directory_path_subuser),
        ),
    ]
