# Generated by Django 2.0 on 2018-01-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20180105_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_alternativo',
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
