# Generated by Django 2.0 on 2018-01-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20180108_1931'),
        ('usuario', '0010_auto_20180108_2116'),
    ]

    operations = [
    ]
