# Generated by Django 2.0 on 2018-03-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20180224_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
