# Generated by Django 2.0 on 2018-03-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20180304_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['usuario__last_name', 'usuario__segundo_apellido']},
        ),
        migrations.AlterModelOptions(
            name='personaladministrativo',
            options={'ordering': ['usuario__last_name', 'usuario__segundo_apellido']},
        ),
        migrations.AlterModelOptions(
            name='personaldocente',
            options={'ordering': ['usuario__last_name', 'usuario__segundo_apellido']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'segundo_apellido']},
        ),
    ]
