# Generated by Django 2.0 on 2018-03-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20180304_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
