# Generated by Django 2.0 on 2018-03-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20180308_2036'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadoestudiante',
            table='estado_estudiante',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
        migrations.AlterModelTable(
            name='personaladministrativo',
            table='personal_administrativo',
        ),
        migrations.AlterModelTable(
            name='personaldocente',
            table='personal_docente',
        ),
        migrations.AlterModelTable(
            name='tipopostgrado',
            table='tipo_postgrado',
        ),
    ]
