# Generated by Django 2.0 on 2018-04-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('unidad_credito', models.IntegerField()),
            ],
            options={
                'db_table': 'asignatura',
                'ordering': ['nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrelacionAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelacionasignatura_asignatura_objetivo', to='asignatura.Asignatura', to_field='codigo')),
                ('asignatura_prela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelacionasignatura_asignatura_prela', to='asignatura.Asignatura', to_field='codigo')),
            ],
            options={
                'db_table': 'prelacion_asignatura',
            },
        ),
        migrations.CreateModel(
            name='TipoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_asignatura',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='tipo_asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignatura.TipoAsignatura'),
        ),
    ]
