# Generated by Django 2.0 on 2018-02-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_auto_20180226_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
