# Generated by Django 2.0 on 2018-03-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0003_auto_20180226_2220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignatura',
            table='asignatura',
        ),
        migrations.AlterModelTable(
            name='tipoasignatura',
            table='tipo_asignatura',
        ),
    ]
