# Generated by Django 2.0 on 2018-03-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0004_auto_20180308_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrelacionAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelacionasignatura_asignatura_objetivo', to='asignatura.Asignatura')),
                ('asignatura_prela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelacionasignatura_asignatura_prela', to='asignatura.Asignatura')),
            ],
            options={
                'db_table': 'prelacion_asignatura',
            },
        ),
    ]
