# Generated by Django 2.0 on 2018-03-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0006_auto_20180311_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre', 'codigo']},
        ),
    ]
