# Generated by Django 2.0 on 2018-04-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'estado_periodo',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('estado_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodo.EstadoPeriodo')),
            ],
            options={
                'db_table': 'periodo',
                'ordering': ['id'],
            },
        ),
    ]
