# Generated by Django 2.0 on 2018-03-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
