# Generated by Django 2.0 on 2018-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0002_periodo_tipo_postgrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='anio_fin',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='periodo',
            name='anio_inicio',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='periodo',
            name='mes_fin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='periodo',
            name='mes_inicio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='periodo',
            name='numero_periodo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
