# Generated by Django 2.0 on 2018-03-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0002_periodo_nombre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadoperiodo',
            table='estado_periodo',
        ),
        migrations.AlterModelTable(
            name='periodo',
            table='periodo',
        ),
    ]
