# Generated by Django 2.0 on 2018-04-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0004_auto_20180308_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['id']},
        ),
    ]
